name: NodeJS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to the server using the remote ssh commands with the private key
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HCAI_HOST }}
        username: ${{ secrets.HCAI_USERNAME }}
        key: ${{ secrets.HCAI_PRIVATE_KEY }}
        port: ${{ secrets.HCAI_PORT }}
        script: 'cd /home/ubuntu/hcais/HCAIs-Surveillance-Web && ./deploy.sh'
